services:
  frontend:
    build:
      context: ../front_meethead
      dockerfile: Dockerfile
    container_name: meethead-frontend
    environment:
      - NODE_ENV=production
      - PORT=11001
      # - NEXT_PUBLIC_NEST_SERVER_URL=http://backend:11002
    ports:
      - "11001:11001"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ../backend_meethead
      dockerfile: Dockerfile
    container_name: meethead-backend
    environment:
      - NODE_ENV=production
      - PORT=11002
    ports:
      - "11002:11002"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: meethead-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_conf:/etc/letsencrypt  
      - certbot_www:/var/www/certbot   
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: meethead-certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    # This command just sleeps. We will run certbot manually.
    entrypoint: sleep
    command: infinity

# --- NEW TOP-LEVEL KEY ---
volumes:
  certbot_conf:
  certbot_www:

networks:
  default:
    name: meethead-network
